#define SCANLINE_FIRST_DISPLAY_PAL 7
#define SCANLINE_LAST_DISPLAY_PAL 307
#define SCANLINE_FIRST_TEXTSAFE_PAL 52
#define SCANLINE_FIRST_DISPLAY_NTSC 11
#define SCANLINE_LAST_DISPLAY_NTSC 261
#define SCANLINE_FIRST_TEXTSAFE_NTSC 30

// times, cycles and clock settings for various points in a scanline...
#define CYCLES_PER_US		(F_CPU / 1000000)

// Note that the NTSC timing is not quite 'correct', but it produces
// a nicely divisible-by-two figure of 1016 cycles per scanline.
#define TIME_SCANLINE_PAL	64
#define TIME_SCANLINE_NTSC	63.5

#define TIME_HALFSCANLINE_PAL	(TIME_SCANLINE_PAL / 2)
#define TIME_HALFSCANLINE_NTSC	(TIME_SCANLINE_NTSC / 2)

#define TIME_HSYNC			4.7
#define TIME_SHORTSYNC		2.35

// NTSC has a smaller back-porch than PAL (hence the earlier start)
#define TIME_DISPLAYSTART_PAL 11.5
#define TIME_DISPLAYSTART_NTSC 10.5

#define CYCLES_HSYNC				(TIME_HSYNC * CYCLES_PER_US)
#define CYCLES_SHORTSYNC			(TIME_SHORTSYNC * CYCLES_PER_US)
#define CYCLES_SCANLINE_PAL			(TIME_SCANLINE_PAL * CYCLES_PER_US)
#define CYCLES_HALFSCANLINE_PAL 	(TIME_HALFSCANLINE_PAL * CYCLES_PER_US)
#define CYCLES_DISPLAYSTART_PAL		(TIME_DISPLAYSTART_PAL * CYCLES_PER_US)
#define CYCLES_SCANLINE_NTSC		(TIME_SCANLINE_NTSC * CYCLES_PER_US)
#define CYCLES_HALFSCANLINE_NTSC	(TIME_HALFSCANLINE_NTSC * CYCLES_PER_US)
#define CYCLES_DISPLAYSTART_NTSC	(TIME_DISPLAYSTART_NTSC * CYCLES_PER_US)

#define CLOCK_HSYNC				(CYCLES_HSYNC - 1 )
#define CLOCK_SHORTSYNC			(CYCLES_SHORTSYNC - 1 )
#define CLOCK_SCANLINE_PAL		(CYCLES_SCANLINE_PAL - 1 )
#define CLOCK_HALFSCANLINE_PAL	(CYCLES_HALFSCANLINE_PAL - 1 )
#define CLOCK_DISPLAYSTART_PAL	(CYCLES_DISPLAYSTART_PAL - 1 )
#define CLOCK_LONGSYNC_PAL		((CYCLES_HALFSCANLINE_PAL - CYCLES_HSYNC) - 1 )
#define CLOCK_SCANLINE_NTSC		(CYCLES_SCANLINE_NTSC - 1 )
#define CLOCK_HALFSCANLINE_NTSC	(CYCLES_HALFSCANLINE_NTSC - 1 )
#define CLOCK_DISPLAYSTART_NTSC	(CYCLES_DISPLAYSTART_NTSC - 1 )
#define CLOCK_LONGSYNC_NTSC		((CYCLES_HALFSCANLINE_NTSC - CYCLES_HSYNC) - 1 )
